### ISSUE TITLE
Specify max error in em, not font units

### ISSUE THREAD

**Issue by behdad** [googlei18n/cu2qu#1]
Right now the max error is in font units (ie 10).  This is problematic, since it means very different things with different fonts.

Change default and meaning of the parameter to be a multiple of unitsPerEm.  Ie. default 0.005, to mean half-percent-of-an-EM error.

**Comment by behdad** [comment]
@anthrotype are you relying on the previous API?  I wonder if it's useful to provide both ways?  Alternatively, we can interpret values >= 1 as being absolute error units, and < 1 as relative.

**Comment by anthrotype** [comment]
yes, I was relying on the previous API that specified the max error in font units. It'd be nice if both was were supported.

**Comment by jamesgk** [comment]
Note that the only function which takes max error in em is `fonts_to_quadratic`, the others all take max error in font units. This is a bit confusing but was much easier to implement (glyph/segment/point objects don't know their own UPM).

Anyways, is it enough to interpret max error in `fonts_to_quadratic` as Behdad described? This would mean that you couldn't specify an error of 0.5 units, for example, so maybe we need an additional optional parameter for max error in font units?

**Comment by jamesgk** [comment]
I'm thinking I will make the `max_err` parameter a value in font units, to be consistent with other functions, then add `max_err_em` which is in em. If `max_err` is given, it is used for all fonts, otherwise `max_err_em` is used with the current fallback of 0.0025.

**Comment by behdad** [comment]
> Note that the only function which takes max error in em is fonts_to_quadratic, the others all take max error in font units. This is a bit confusing but was much easier to implement (glyph/segment/point objects don't know their own UPM).

Right.

> Anyways, is it enough to interpret max error in fonts_to_quadratic as Behdad described? This would mean that you couldn't specify an error of 0.5 units, for example, so maybe we need an additional optional parameter for max error in font units?

Ok, in the interest of least surprise, let's add a new argument.  May I suggest that:

  * instead of using kwargs, spell-out all arguments.  This makes the function signature more useful.

  * rename `max_err` to tolerance and `max_errors` to tolerances, and it will be the absolute max error,

  * add `tolerance_units` and `tolerances_units` that are in font units of each master.  Set both of these args to None in the function signature, and check that exactly one is specified.  I think we should remove the default value for these and just document a good value.

  * For both tolerances and `tolerances_units` if a scalar is specified, use that number for all masters,

  * Is `max_n` useful at all?  Our algorithm is robust, and it converges (if we fix issue 6 and issue 7), so I don't see how `max_n` would be useful or what it would be used for.  I suggest removing it completely.  You can have an internal max_n (perhaps derived from tolerance, maybe not, hardcode 100?), and if we exceed that, err, print the curves and tolerance and request that a bug be filed.

**Comment by behdad** [comment]
> I'm thinking I will make the max_err parameter a value in font units, to be consistent with other functions, then add max_err_em which is in em. If max_err is given, it is used for all fonts, otherwise max_err_em is used with the current fallback of 0.0025.

Oh right, better be consistent, yes.

**Comment by anthrotype** [comment]
I'd suggest we keep this issue open until we address all the points raised by @behdad in https://github.com/googlei18n/cu2qu/issues/1#issuecomment-159394830 above

I don't like the use of kwargs in `fonts_to_quadratic`.

Also, I think the `max_n` parameter should be either dropped altogether, as Behdad suggested, or it could be used as an alternative to specifying the max tolerance: i.e., give me the quadratic spline that approximates this cubic bezier and only use `max_n` segments, whatever the distance is. Though I'm not 100% sure this would be useful either.
