### ISSUE TITLE
module 'cu2qu' has no attribute 'ufo'

### ISSUE THREAD

**Issue by laerm0** [googlei18n/cu2qu#180]
Hello –

I was trying to use this on my Open Sans work but it looks like the skeleton of a script provided is incorrect. @felipesanches was helping me with the script and it looks like that the module isn't as documented in the readme.

My script:

```
from defcon import Font
import cu2qu
import ipdb; ipdb.set_trace()


light_font = Font('source/Open Sans-Light.ufo')
bold_font = Font('source/Open Sans-Bold.ufo')
extrabold_font = Font('source/Open Sans-ExtraBold.ufo')
lightcond_font = Font('source/Open Sans-Light Condensed.ufo')
boldcond_font = Font('source/Open Sans-Bold Condensed.ufo')
extraboldcond_font = Font('source/Open Sans-ExtraBold Condensed.ufo')

cu2qu.ufo.fonts_to_quadratic([light_font, bold_font, extrabold_font, lightcond_font, boldcond_font, extraboldcond_font])
```

running in `ipdb`:

<img width="1053" alt="screenshot_2019-04-11_23-11-59" src="https://user-images.githubusercontent.com/10780161/56016632-c1afc700-5cb1-11e9-93ef-b6766bd4474a.png">

**Comment by anthrotype** [comment]
Yes, like the error said. You should import like this:

from cu2qu.ufo import fonts_to_quadratic

or if you like the fully qualified import:

import cu2qu.ufo

Then you use it like:

cu2qu.ufo.fonts_to_quadratic

BTW, why don’t you just use the cu2qu console script?

**Comment by laerm0** [comment]
I changed my script to read:

```
from defcon import Font
from cu2qu.ufo import fonts_to_quadratic

# import ipdb; ipdb.set_trace()


light_font = Font('source/Open Sans-Light.ufo')
bold_font = Font('source/Open Sans-Bold.ufo')
extrabold_font = Font('source/Open Sans-ExtraBold.ufo')
lightcond_font = Font('source/Open Sans-Light Condensed.ufo')
boldcond_font = Font('source/Open Sans-Bold Condensed.ufo')
extraboldcond_font = Font('source/Open Sans-ExtraBold Condensed.ufo')

cu2qu.ufo.fonts_to_quadratic([light_font, bold_font, extrabold_font, lightcond_font, boldcond_font, extraboldcond_font])
```

Same error:
`NameError: name 'cu2qu' is not defined`

<img width="1440" alt="screenshot_2019-04-12_01-04-38" src="https://user-images.githubusercontent.com/10780161/56021758-160d7380-5cbf-11e9-86e7-ae4b07a3b1dc.png">

> BTW, why don’t you just use the cu2qu console script?

I didn't know there was one. There's nothing about it in the readme.

**Comment by anthrotype** [comment]
if you did `from cu2qu.ufo import fonts_to_quadratic`, then you call the function as `fonts_to_quadratic`, without `cu2qu.ufo` in front.

> I didn't know there was one.

I believe I did mention it in our private email conversation.

> There's nothing about it in the readme.

Fair enough :) We shold add a reference to that in the README.md

**Comment by anthrotype** [comment]
I updated README
https://github.com/googlei18n/cu2qu/commit/e8e8ddebb4ef8e15d8e14ab820883f1d619aa4c2

**Comment by laerm0** [comment]
Ahhhh, I see now. Sorry I missed that in the email thread. Thanks very much, I am good now. Sorry to bug you. :)

**Comment by anthrotype** [comment]
Np, feel free to "debug" me :)
