### ISSUE TITLE
ufo.py: hook for converting a single glyph

### ISSUE THREAD

**Issue by LettError** [googlei18n/cu2qu#26]
`_fonts_to_quadratic` converts the whole font.
`_segments_to_quadratic` converts a set of segments. 

I'd be interested in something in the middle, like `glyphs_to_quadratic` that I can feed a list of robofab / defcon glyphs. It could be derived from `_fonts_to_quadratic` which needs to iterate through the objects in the font and then call `glyphs_to_quadratic` and return the converted glyphs.

**Comment by anthrotype** [comment]
Yeah, we discussed about that some time ago: https://github.com/googlei18n/cu2qu/pull/20#issuecomment-213020406
But then I got busy with other stuff. If someone else wants to pick this up before I do, you're welcome... ;)

**Comment by anthrotype** [comment]
of course, if you don't care about interpolatability and simply want to convert a single glyph (like the title of this issue says), then you can simply use the Cu2QuPen or the Cu2QuPointPen as usual.

**Comment by LettError** [comment]
Ah no, sorry. Convert a /set/ of glyphs, each from different UFOs?

Erik
