### ISSUE TITLE
fonts_to_quadratic([thin_font, bold_font])

### ISSUE THREAD

**Issue by antonxheight** [googlei18n/cu2qu#27]
Not really an issue. 
I wanted to give try to your cu2qu curves converter.
Could you please give a tip how to save the converted:
_fonts_to_quadratic([thin_font])_
to a new UFO file. Quick test showed that original UFO is not modified by the script.

I tried to pass it to Robofab UFOwriter, but apparently fonts_to_quadratic returns a dictionary with curve stats.
Thanks,
Anton

**Comment by adrientetar** [comment]
[Here's](https://github.com/googlei18n/fontmake/blob/166af90d676fd33d5a05d0bc2cddf047f696e147/Lib/fontmake/font_project.py#L129) how fontmake does it.

Please post your script if you have an issue, otherwise we can't track it down.

**Comment by antonxheight** [comment]
Obviously i had tried **fontmake** before writing here. That script has _save_otfs_ which has saving abilities closest to what is needed (that is saving UFOs). Installing all the dependencies took quite some time and on Windows Fontmake didn't work (Bool operation if i remeber right).
Prior to writing here i also read thoroughly **jamesgk** original cu2qu source as well. Module .py files are named differently there (rf.py vs UFO.py +pens.py have been appended)

My initial code *idea was:

from defcon import Font
from cu2qu.ufo import fonts_to_quadratic, font_to_quadratic              
thin_font = Font('/Users/delku2/Desktop/cu2qu_test/09b-ak.ufo')
mfont = fonts_to_quadratic([thin_font], max_err_em=0.005)
#mfont = Font(mfont)
mfont.save
print "done"

Which was naive.

**Comment by anthrotype** [comment]
fonts_to_quadratic does not return a converted copy, it updates the font instances in place. Just do thin_font.save("path/to/thin_font_quad.ufo").

**Comment by antonxheight** [comment]
I see, now i Got it.
Thank you very much!
