### ISSUE TITLE
In stats report, return number of segments, not points

### ISSUE THREAD

**Issue by behdad** [googlei18n/cu2qu#39]
I find it very confusing that we are reporting '3' instead of '1' when a cubic is replaced by one quadratic.

**Comment by jamesgk** [comment]
I'm fine with this. The reason I returned points, btw, was to make the comparison with old curves easier (remembering that cubics have four points was easier than remembering they have the same number of points as a two-segment spline). Obviously not a big deal though.

**Comment by behdad** [comment]
Right.  I see.
