### ISSUE TITLE
Better reporting on ValueError in ufo.py

### ISSUE THREAD

**Issue by LettError** [googlei18n/cu2qu#46]
Not a bug, but a request. For debugging purposes of font data it would be helpful to see which glyph trips the ValueError in ufo.py line 47.
`ValueError: Args to zip in cu2qu should have equal lengths: [('move', ((244, 489),)), ('curve', ((244, 489)..[etc]`

**Comment by mrecord** [comment]
This  seems to have gotten worse in the last update.
`ValueError: Args to zip in cu2qu should have equal lengths: <defcon.objects.font.Font object at 0x1041fc310> <defcon.objects.font.Font object at 0x104330890>`
