### ISSUE TITLE
drop robofab support?

### ISSUE THREAD

**Issue by anthrotype** [googlei18n/cu2qu#57]
I would like to get rid of the `try: import ufoLib; except ImportError: import robofab` stuff and only require `ufoLib`.

Robofab is py2 only, and is no longer actively maintained. Even though it might be slightly faster than defcon+ufoLib in the `cu2qu.ufo_benchmark`, I think we can't keep supporting both backends for long.

It'd be just easier if we only support ufoLib, so I can specify the latter as `install_requires` in the setup.py.

Alternatively, we could have robofab as an optional `extras_require`, so people who wishes to use cu2qu with robofab could do `pip install cu2qu[robofab]`. But then we will have to maintain robofab (e.g. run tests against it on the CI).

I suggest we drop it.

**Comment by anthrotype** [comment]
I no one turns up by tomorrow morning in favour of keeping robofab support, I'm gonna kill it in the next release.

**Comment by miguelsousa** [comment]
Sounds good to me

**Comment by anthrotype** [comment]
done af0a06081a88b3cf8163a649185cf507dd41f44f
