### ISSUE TITLE
Consider inserting inflexion points

### ISSUE THREAD

**Issue by adrientetar** [googlei18n/cu2qu#60]
Cubics with implicit inflexion points can look kinda bad once converted into quads... It would probably be wise to insert them.

Doing this and keeping compatibility might be a bit of a head scratch, I reckon.

**Comment by anthrotype** [comment]
Do they? Have you got a screenshot?

**Comment by behdad** [comment]
Do you have examples?   I agree we should break on cusps, but not on inflection points.

**Comment by be5invis** [comment]
There was an example in the Node module `cubic2quad`: https://github.com/fontello/cubic2quad/issues/1

**Comment by behdad** [comment]
Oh that's just a bug in that algorithm.  Ours is robust against inflection points. We do need to handle cusps though: https://github.com/googlei18n/cu2qu/issues/6
Cosimo, feel like addressing that?
