### ISSUE TITLE
change the default approximation error?

### ISSUE THREAD

**Issue by anthrotype** [googlei18n/cu2qu#76]
The current `DEFAULT_MAX_ERR` value is set to 0.0025 of the UPEM, e.g. 2.5 units in 1000 UPEM.

Our designers at DaMa feel that this value is a bit too generous, thus we opted for a stricter value of 0.001 which produces more accurate results, of course with the greater cost in terms of file size.

I would like to hear from others who use cu2qu what they think, if you use the default value or a custom one, and whether you would agree on changing the default conversion tolerance.

**Comment by marekjez86** [comment]
@anthrotype : what would be file size difference with 0.001? Why is 0.0025 of the UPEM too generous (i.e., what the visible effect of this)?

**Comment by anthrotype** [comment]
When I have some time, I will produce some comparisons, maybe taking some Noto font as reference, overlaying the outputs of different approximation values over the original cubic outlines.

**Comment by marekjez86** [comment]
IMHO: we should change the value to 0.001

**Comment by anthrotype** [comment]
I would not rush this, as people may be relying on the current default settings, and changing these may for example invalidate hinting data that depends on the index of the points.
If we decide to change it, then we should probably cut a major release and make it clear to users that the quadratic outlines will be different if they were relying on the default value, instead of explicitly setting a custom one.

**Comment by marekjez86** [comment]
@brawer @lemzwerg :  what do you think of the 0.001 ... how much it would impact auto-hinting etc...?

**Comment by anthrotype** [comment]
ttfautohint-ing should not be affected, unless one uses a control file to make local adjustments (which is tied to the node count).

**Comment by behdad** [comment]
Anyone relying on our exact output is asking for trouble.  We don't guarantee the algorithm doesn't change.

As for changing default, I tend to agree.  Current number is too high and Jelle has been nagging about it for a long time.

I like to see we add a repository of curves in fonttools, for testing.  These can come from a variety of Latin and non-Latin fonts, organized in various corpora.  Then we can measure changes like these before making decisions.
